name: OONI Explorer End-to-End Tests
on: [push]
jobs:
  cypress-e2e:
    strategy:
      matrix:
        # maybe drop `edge` if it fails too often
        browser: [firefox, chrome, edge]
    runs-on: ubuntu-latest
    name: E2E test on ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3100'
          browser: ${{ matrix.browser }}

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
